### ISSUE TITLE
Add some cool feature or improve something

### ISSUE THREAD

**Issue by cyruzin** [cyruzin/movie_discovery#2]

**Comment by hendaoui** [comment]
I will try to improve the design

**Comment by g-ravity** [comment]
I would like to work on this. I can improve the UI and add "Add to Watchlist" feature

**Comment by cyruzin** [comment]
Go ahead :)

**Comment by olzh2102** [comment]
I would like to work on this as well. I can refactor the components

**Comment by cyruzin** [comment]
> I would like to work on this as well. I can refactor the components

Nice.
